; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.42"

; Modules
projects[views_bulk_operations][version] = "3.3"

projects[addressfield][version] = "1.2"

projects[admin][version] = "2.0-beta3"

projects[admin_menu][version] = "3.0-rc5"

projects[auto_nodetitle][version] = "1.0"

projects[block_class][version] = "2.3"

projects[ctools][version] = "1.9"

projects[bundle_copy][version] = "1.1"

projects[coffee][version] = "2.2"

projects[commerce][version] = "1.11"

projects[commerce_addressbook][version] = "2.0-rc9"

projects[commerce_autosku][version] = "1.1"

projects[commerce_backoffice][version] = "1.5"

projects[commerce_coupon][version] = "2.0-rc2"

projects[commerce_discount][version] = "1.0-alpha7"

projects[commerce_features][version] = "1.1"

projects[commerce_invoices][version] = "1.0"

projects[commerce_paypal][version] = "2.3"

projects[commerce_saleprice][version] = "1.0-beta4"

projects[computed_field][version] = "1.1"

projects[content_access][version] = "1.2-beta2"

projects[context][version] = "3.6"

projects[date][version] = "2.9"

projects[delta][version] = "3.0-beta11"

projects[easy_breadcrumb][version] = "2.12"

projects[email_auto_login][version] = "1.1"

projects[entity][version] = "1.6"

projects[entitycache][version] = "1.5"

projects[entityform][version] = "2.0-rc1"

projects[entityreference][version] = "1.1"

projects[entityreference_prepopulate][version] = "1.6"

projects[eva][version] = "1.2"

projects[features][version] = "2.7"

projects[fences][version] = "1.2"

projects[file_entity][version] = "2.0-beta2"

projects[flexslider][version] = "2.0-rc1"

projects[google_analytics][version] = "2.1"

projects[honeypot][version] = "1.21"

projects[panels][version] = "3.5"

projects[imce][version] = "1.9"

projects[imce_filefield][version] = "1.1"

projects[imce_wysiwyg][version] = "1.0"

projects[inline_conditions][version] = "1.0-alpha7"

projects[inline_entity_form][version] = "1.6"

projects[libraries][version] = "2.2"

projects[link][version] = "1.4"

projects[logintoboggan][version] = "1.5"

projects[masquerade][version] = "1.0-rc7"

projects[media][version] = "2.0-beta1"

projects[menu_block][version] = "2.7"

projects[menu_token][version] = "1.0-beta6"

projects[message][version] = "1.11"

projects[message_notify][version] = "2.5"

projects[module_filter][version] = "2.0"

projects[node_export][version] = "3.0"

projects[og][version] = "2.7"

projects[options_element][version] = "1.12"

projects[pathauto][version] = "1.3"

projects[pathologic][version] = "3.1"

projects[pm_existing_pages][version] = "1.4"

projects[responsive_menus][version] = "1.5"

projects[services][version] = "3.13"

projects[robotstxt][version] = "1.3"

projects[rules][version] = "2.9"

projects[securelogin][version] = "1.6"

projects[select_or_other][version] = "2.22"

projects[strongarm][version] = "2.0"

projects[styleguide][version] = "1.1"

projects[superfish][version] = "2.0"

projects[support][version] = "1.0-rc2"

projects[taxonomy_edge][version] = "1.9"

projects[token][version] = "1.6"

projects[uuid][version] = "1.0-beta1"

projects[views][version] = "3.13"

projects[views_megarow][version] = "1.5"

projects[views_slideshow][version] = "3.1"

projects[webform][version] = "4.12"

projects[workflow][version] = "2.8"

projects[wysiwyg][version] = "2.2"

; Themes
projects[omega][version] = "4.4"

projects[zen][version] = "5.6"

; Libraries
libraries[chosen][download][type] = git
libraries[chosen][download][url] = https://github.com/mikebrew/chosen.git
libraries[chosen][destination] = libraries
libraries[chosen][directory_name] = chosen
libraries[chosen][download][branch] = master

libraries[superfish][download][type] = git
libraries[superfish][download][url] = https://github.com/mikebrew/superfish.git
libraries[superfish][destination] = libraries
libraries[superfish][directory_name] = superfish
libraries[superfish][download][branch] = master

libraries[ckeditor][download][type] = git
libraries[ckeditor][download][url] = https://github.com/mikebrew/ckeditor.git
libraries[ckeditor][destination] = libraries
libraries[ckeditor][directory_name] = ckeditor
libraries[ckeditor][download][branch] = master

;libraries[jquerycycle][download][type] = git
;libraries[jquerycycle][download][url] = https://github.com/mikebrew/jquery.cycle.git
;libraries[jquerycycle][destination] = libraries
;libraries[jquerycycle][directory_name] = jquery.cycle
;libraries[jquerycycle][download][branch] = master

libraries[flexslider][download][type] = git
libraries[flexslider][download][url] = https://github.com/woothemes/FlexSlider.git
libraries[flexslider][destination] = libraries
libraries[flexslider][directory_name] = flexslider
libraries[flexslider][download][branch] = master

libraries[html5shiv][download][type] = git
libraries[html5shiv][download][url] = https://github.com/aFarkas/html5shiv.git
libraries[html5shiv][destination] = libraries
libraries[html5shiv][directory_name] = html5shiv
libraries[html5shiv][download][branch] = master

libraries[selectivizr][download][type] = git
libraries[selectivizr][download][url] = https://github.com/keithclark/selectivizr.git
libraries[selectivizr][destination] = libraries
libraries[selectivizr][directory_name] = selectivizr
libraries[selectivizr][download][branch] = master

libraries[respond][download][type] = git
libraries[respond][download][url] = https://github.com/scottjehl/Respond.git
libraries[respond][destination] = libraries
libraries[respond][directory_name] = respond
libraries[respond][download][branch] = master

libraries[pie][download][type] = git
libraries[pie][download][url] = https://github.com/lojjic/PIE.git
libraries[pie][destination] = libraries
libraries[pie][directory_name] = pie
libraries[pie][download][branch] = master

libraries[hybridauth][type] = git
libraries[hybridauth][download][url] = https://github.com/hybridauth/hybridauth.git
libraries[hybridauth][destination] = libraries
libraries[hybridauth][directory_name] = hybridauth
libraries[hybridauth][download][branch] = master

libraries[fullcalendar][type] = get
libraries[fullcalendar][download][url] = https://github.com/arshaw/fullcalendar/releases/download/v2.1.1/fullcalendar-2.1.1.zip
libraries[fullcalendar][destination] = libraries
libraries[fullcalendar][directory_name] = fullcalendar
